### ISSUE TITLE
Errors occur in libSpatialSEIR

### ISSUE THREAD

**Issue by PatriciaXiao** [grantbrown/Ebola-2014-Analysis-Archive#1]
I do admire, and am really grateful of your great work done in libSpatialSEIR. However, I wonder if there are some, if not many, bugs, in the temporary version. Would it be possible that your new APIs or so caused trouble so that the whole project could not be run as it supposed to be?

Thanks a lot, and sorry to have bothered you so much. But I believe you have the right to know whether there is anything wrong with your project.

Best wishes, to both you and libSpatialSEIR.

**Comment by PatriciaXiao** [comment]
For more details, first of all installation was a struggle, and then, without examples, it is really difficult to use it ... Well, it was a little bit easier to make it work (possibly) in Linux. As for Windows, excuse me, are you sure the .bat would work ... ?

**Comment by PatriciaXiao** [comment]
Hello, sir?

**Comment by PatriciaXiao** [comment]
I'm sorry it's midnight here in China, I have to go to bed now ... (QwQ)

Good night.

**Comment by grantbrown** [comment]
Hi Patricia, 

Indeed, the latest version of [libSpatialSEIR](https://github.com/grantbrown/libspatialSEIR) is no longer compatible with the analyses presented in this repository ([Ebola-2014-Analysis-Archive](https://github.com/grantbrown/Ebola-2014-Analysis-Archive)). The software is still evolving quickly, so there are bound to be bugs. Once I finish the new qSEIR API I will update the Ebola analyses and work on expanding the documentation (as you've noticed, there isn't nearly enough). Once this is complete, I will create a release version, which will change far less frequently. 

As a side note, I have made sure to keep [the companion repository](https://github.com/grantbrown/EARNMC.git) to our recently submitted manuscript up to date, so that might be a good place to look at examples in the meantime. 

Installation is a bit tough, but I am successfully using the software on a Windows machine. If you could open an issue on the main repository [here](https://github.com/grantbrown/libspatialSEIR/issues) with specific error messages, that would be helpful. Once version 1.0 is released, I will provide a Windows installer which should simplify this process greatly. 

As for the library itself, the biggest recent change is that I eliminated the separate X and Z matrices (time invariant and time varying covariates in the intensity process) in favor of a single X matrix. This change should simplify the model specification process, and was necessary for the development of the simpler qSEIR modeling functions I'm creating. If it is these changes which are causing you problems, I did add a function called "buildExposureModel_depricated" which preserves the old API for users who don't want to re-do their models. Again, if you're running into errors it would be helpful to see both your code and the resulting errors [here](https://github.com/grantbrown/libspatialSEIR/issues). 

Hope that helps,
-Grant

**Comment by PatriciaXiao** [comment]
Hi Grant:

Oh wow, you replied so quickly and patiently that I could hardly find a word to express my feeling.

Yes it really helps a lot!

Thank you very much!

-Patricia

**Comment by grantbrown** [comment]
No problem. As a heads up, I just noticed that I neglected to add a new header file (should have been added along with [these changes on 2/6](https://github.com/grantbrown/libspatialSEIR/commit/289135abd43c7cf60cba1d6e52836974ad6a68e2)) to the repository. This would have made building the latest version impossible, and might be to blame for your difficulties. This issue has now been fixed.
